/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 88f42f832059cd0f36b2951855231459)
interface __BaseEnv_Env {
	GROKPLACE: KVNamespace;
	EDGE_READ_LIMITER: RateLimit;
	EDGE_WRITE_LIMITER: RateLimit;
	EDGE_LIVE_LIMITER: RateLimit;
	EDGE_CHALLENGE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	COOLDOWN_MS: "30000";
	CANVAS_SIZE: "128";
	CANVAS: DurableObjectNamespace<import("./worker/index").GrokPlaceCanvas>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "GrokPlaceCanvas";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
